### ISSUE TITLE
Is it possible to tell copy-webpack-plugin to be less verbose ?

### ISSUE THREAD

**Issue by RPDeshaies** [webpack-contrib/copy-webpack-plugin#113]
Because if I copy 2000 files, its going to `console.log` them all in the assets table of webpack.

**Comment by alerkesi** [comment]
Guys, is there some answer please?

**Comment by Stanback** [comment]
@alerkesi You could add `stats: { assets: false }` to your webpack configuration to silence the list of files. The downside is it will hide *all* assets rather than just the ones copied by this plugin.

If you want to selectively log assets, it seems like that would have to be a new feature added to webpack itself. You could also get tricky and use the webpack node API to run webpack, grab the stats string, and filter it before outputting.

**Comment by Predjo** [comment]
With the new version of webpack you can filter the log by doing something like this:

```  
stats : {
    assets : true,
    excludeAssets : [/.*vendor\/.*/ , /.*assets\/.*/],
  }
```

More info in the [docs](https://webpack.js.org/configuration/stats/).

**Comment by cletusw** [comment]
@Predjo 's solution worked for me. This issue should be closed as Resolved.

**Comment by thw0rted** [comment]
It's in the docs, but if anybody else here failed to click through initially and was disappointed that this "didn't work", be aware that `devServer` gets its own copy of this config item.  If you want to thin out your console output in dev mode, you'll need `stats: { ... }` there too.
