### ISSUE TITLE
Import & Typescript support 

### ISSUE THREAD

**Issue by ietabhi** [webpack-contrib/copy-webpack-plugin#268]
When i convert to typescript, below code not working:-

import * as CopyWebpackPlugin from 'copy-webpack-plugin';

const config = {
  plugins: [
    new CopyWebpackPlugin([ ...patterns ], options)
  ]
}

**Comment by evilebottnawi** [comment]
@ietabhi how it is related to plugin, looks you don't know how to right way use typescript

**Comment by ietabhi** [comment]
Getting error when compiling  : Only a void function can be called with the 'new' keyword

**Comment by ericdrobinson** [comment]
I'm encountering the same issue when using a `[jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig)` file to assist in type-checking the Webpack config files as JavaScript. This generates the following two errors:

>Only a void function can be called with the 'new' keyword.

The problem here is that the `CleanWebpackPlugin` is a function that [explicitly returns a new object](https://github.com/webpack-contrib/copy-webpack-plugin/blob/5474889d9a72d1a51eb86995cc71fab843e60eb1/src/index.js#L170). When called, all the properties and settings are wrapped up (captured) in the [`apply` function](https://github.com/webpack-contrib/copy-webpack-plugin/blob/5474889d9a72d1a51eb86995cc71fab843e60eb1/src/index.js#L43) and returned as a new anonymous object instance.

Therefore, there is no need to use the `new` keyword with `CopyWebpackPlugin`. You simply adjust your code to the following:

```ts
import * as CopyWebpackPlugin from 'copy-webpack-plugin';

const config = {
    plugins: [
        CopyWebpackPlugin([ ...patterns ], options)
    ]
}
```

That should clear up any errors that you see. Did for me in the pure JavaScript space. I further tested it by adding multiple calls to `CopyWebpackPlugin()` in the same `plugins` array and everything worked as expected.

If someone knows of a reason why the `new` keyword _would_ be necessary here, please let us know!

---
As a side note, I have the `strict` [compilerOption](https://www.typescriptlang.org/docs/handbook/compiler-options.html) enabled in my `jsconfig.json` file. This results in another error:

>'new' expression, whose target lacks a construct signature, implicitly has 'any' type.

This issue is "resolved" in the same manner as above: remove the `new` keyword in use.

**Comment by evilebottnawi** [comment]
Looks bug :confused: Feel free to send PR

**Comment by ericdrobinson** [comment]
@evilebottnawi This isn't a bug: it's a design choice. It's inconsistent with most Webpack plugins, of course, but it's not specifically "broken".

"Fixing" this would mean rearchitecting it such that it conformed to standard (classic) JavaScript "class" architecture. For a pretty straightforward example, check out the [CleanWebpackPlugin source](https://github.com/johnagan/clean-webpack-plugin/blob/e9895d304f68a0c64eb4a89486074603d4937aef/index.js). In that code you'll see that:

1. The [constructor object](https://github.com/johnagan/clean-webpack-plugin/blob/e9895d304f68a0c64eb4a89486074603d4937aef/index.js#L22) is just a function definition **without** a `return` statement.
1. The `apply` function is attached to the constructor object's [prototype](https://github.com/johnagan/clean-webpack-plugin/blob/e9895d304f68a0c64eb4a89486074603d4937aef/index.js#L183).
1. It does some specific handling of [`this`](https://github.com/johnagan/clean-webpack-plugin/blob/e9895d304f68a0c64eb4a89486074603d4937aef/index.js#L184) for various contexts, likely to support various calling conventions.

Addressing this would require a larger rearchitecture of the plugin code. I would recommend that one of the maintainers drive/guide such a transition, rather than request a community PR.
