### ISSUE TITLE
No automatic reload when using HMR

### ISSUE THREAD

**Issue by data-ux** [webpack-contrib/copy-webpack-plugin#270]
When using Hot Module Replacement with `webpack-dev-server --hot`, any changes to assets copied by copy-webpack-plugin will result in new compilation, but the browser HMR code thinks it can succesfully apply a hot update and does not reload the page. Manual browser reload is needed to load the changed assets.

What would need to happen is a HMR update failure, after which webpack-dev-server reloads automatically.

**Comment by OfficerHalf** [comment]
I have the same issue. For my project, we have our own code, but also consume another large library. While our code is bundled up and HMR handles it nicely, the 3rd party code (and the changes we make to that code) are not reloaded because they are copied and served, rather than bundled.

The changes are detected, but no reload occurs.

**Comment by evilebottnawi** [comment]
If problem still exists, please create issue in `webpack-dev-server`, we use standard `webpack` api

**Comment by BeSaRa** [comment]
any solution here , issue still exists!! any advise ??

**Comment by xBau** [comment]
Same issue here. Sadly to see that there is no solution after 1 year.

Great plugin anyway :)

**Comment by githoniel** [comment]
Same issue here.

**Comment by infime** [comment]
As someone new to webpack I'm kind of stunned that this hasn't been addressed yet. Has anyone found any viable alternatives? My use case is very simple.

**Comment by whudson** [comment]
Have the same issue. It looks like there is not any module.hot.accept in copy webpack plugin so I am not sure the issue is here?
