### ISSUE TITLE
Unclear `context` parameter doco.

### ISSUE THREAD

**Issue by stevage** [webpack-contrib/copy-webpack-plugin#456]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The `context` parameter:

> A path that determines how to interpret the from path.

I honestly could not make any sense of this. I'm new to Webpack and reading someone else's config file where they have used this parameter. I still have no idea what it does.

### Your Proposal for Changes

I don't really have one. From [this stackoverflow issue](https://stackoverflow.com/questions/45036810/webpack-copying-files-from-source-to-public-using-copywebpackplugin/45038597) I suspect that the right description would be something like:

> The `context` part of the path will be stripped out of the `from` path when determining the final path

But I'm not really sure.

**Comment by sarahdayan** [comment]
This is indeed unclear in the docs, but this is exactly what the StackOverflow issue that you linked says. The `context` option allows you to specify a context to narrow down your `from` glob.

So, let's say this is your configuration:

```js
new CopyPlugin([
  {
    from: '**/*',
    context: './public/'
  },
])
```

Here, the plugin will retrieve all files recursively (`**/*`) from the `public` directory. This differs from doing `public/**/*` because in that case, you'd be reproducing the entire path, including `public`.

This deserves a doc edit, I'll do it if nobody does before me 🙂

**Comment by stevage** [comment]
Ah thanks, I definitely understand it much better now.

So maybe something like:

> the path within the project where the relative `from` path is applied. (Defaults to the root).

But probably also needs to explain the "why", which you did well.
