### ISSUE TITLE
Make it possible to prevent optimizatoin of copied files

### ISSUE THREAD

**Issue by ninze** [webpack-contrib/copy-webpack-plugin#551]
After upgrading to webpack 5, copy-webpack-plugin started to optimize *.js files that it copies in production mode. One would expect that a "copy" plugin would copy files byte by byte without modifying them. I could not find a way to prevent this behavior. Tried to provide the `transform` function which returns unmodified content, but that didn't help.

webpack: 5.1.3
copy-webpack-plugin": 6.2.1

**Comment by sibiraj-s** [comment]
It is expected Since v6. @evilebottnawi's comment here. See https://github.com/webpack-contrib/copy-webpack-plugin/issues/526#issuecomment-688773341

You might need to exclude the manually in TerserPlugin, using `test/include/exclude` options.

> One would expect that a "copy" plugin would copy files byte by byte without modifying them.

This plugin adds the assets into compilation. So I guess, webpack will try to do its work there.

cc @evilebottnawi

**Comment by evilebottnawi** [comment]
@sibiraj-s Yes, thanks for answe

@ninze Please use `test`/`include`/`exclude`
