### ISSUE TITLE
[Feature] Support `context` globs

### ISSUE THREAD

**Issue by KingScooty** [webpack-contrib/copy-webpack-plugin#58]
I have a series of react components in folders that all have their own `images` folder. I'd really like to be able to glob the context and then copy the images and folders inside that context to a destination. 

Is this ^^ possible? I've tried the following, but it doesn't seem to work:

``` js
new CopyWebpackPlugin([
  {
    context: `${__dirname}/src/**/images`,
    from: '**/*',
    to: path.join(__dirname, '.temp/static/images/')
  }
]),
```

And doing:

``` js
new CopyWebpackPlugin([
  {
    context: `${__dirname}/src/`,
    from: '**/images/**/*',
    to: path.join(__dirname, '.temp/static/images/')
  }
]),
```

Has the annoying consequence of copying all the parent folders to `images`. 

e.g: `.temp/static/images/components/posts/images/2x/header.png`

I could use `flatten: true` to remove the parent folders, but that would also remove the child folders _inside_ of the component `images` folder, and i want to preserve them :(

**Comment by kevlened** [comment]
Globs in contexts aren't supported. It's an interesting use case though.

**Comment by urbanhusky** [comment]
Why aren't they? I mean, I just wasted a good part of the day trying to get something similar to work.
In our case, we have `app/assets` which contain all kinds of images, fonts etc. Most of them are not correctly picked up by webpack (partially because we have a lot of 3rd party bootstrap code that uses strings to reference assets).

Therefore we want to copy everything from `app/assets/**/*` to `wwwroot/dist/assets/**/*`.
I thought I could define it as such:
*helpers is a module that returns the root path of the application, regardless of where it is used*
```ts
new CopyWebpackPlugin([{
	context: helpers.root('app','assets'),
	from: {
		glob: '**/*',
		dot: true
	},
	to: helpers.root('wwwroot','dist','assets')
}])
```

Are there any other ways to achieve the same effect? I don't want to have to specify every single folder or file because we will end up forgetting to copy some of those later on.

**Comment by DenisVuyka** [comment]
The latest version does not seem to work with Glob correctly, at least with something more complex than `**/*`. The following pattern works with `glob` perfect but fails with `copy-webpack-plugin`:

```json
{
  "context": "<source>",
  "from": "prefix-+(option1|option2)*/subfolders/*.json",
  "to": "<dest>"
}
```

**Comment by evilebottnawi** [comment]
Impossible to solve due file collision as described above
