### ISSUE TITLE
What are _the right_ use cases for this plugin.

### ISSUE THREAD

**Issue by TheLarkInn** [webpack-contrib/copy-webpack-plugin#70]
My self, and other webpack team members we're wondering what the _right_ usecases for this plugin are? 

I was finding myself, struggling between telling people to _not_ use it or use the plugin if they simply want to have their assets _not_ bundled and emitted to the dist folder etc. However that would be an anti-pattern for what webpack is trying to accomplish (managing all assets in a project). Most time url+file loader with a small limit accomplishes this out of the box for any asset you load. 

@kevlened What advice can I give users when they say "when should I be using copy-webpack-plugin". And maybe we can document some of this on the project so that people can understand the intent and best practices etc.  Thank you for this project and maintaining it

**Comment by asabil** [comment]
I just stumbled upon this plugin, and the use case is config management. Basically the app is built using webpack, but it needs to load a JSON config file at runtime.

**Comment by TheLarkInn** [comment]
That's a good case! Only playing devil's advocate: how would that differ if you instead used json-loader and assign to a variable or service etc.

**Comment by asabil** [comment]
I ended up using plain webpack (file-loader + xhr request on app load). Couldn't get this plugin to work properly with webpack-dev-server.

If I create a separate chunk using json-loader, that chunk is no longer a json file once processed with webpack. This makes it pretty much unusable when configuring your SPA at deployment time.

**Comment by Alex-Krautmann** [comment]
Like @asabil, I am looking into the best way to handle this situation. I am currently trying out [Astrum](http://astrum.nodividestudio.com/) to generate a styleguide for an angular component library. 

The output of the build is the component library as a chunk and the styleguide app as a chunk. The styleguide app is mostly generated using Astrum. When the styleguide/astrum app starts, it makes a request for data.json which it then uses to create the styleguide.

The way Astrum creates the styleguide is by going through the styleguide app's folder structure and generating HTML for the markdown files that contain the documentation for each component.

I realize this is a very specific use case and perhaps not the best design for a web app. I would prefer if Spectrum was more typical and I could bring it in as a module and use it in the normal fashion with Webpack.

Things work OK on the dev server, since I have specified the baseDir to be the source styleguide. But this is not really the final solution. Eventually, this styleguide will be hosted internally and I need the build folder to contain these markdown and json files. I am coming to the conclusion that I will need to use the copy-plugin to make this work, given the current constraints.

I agree that this plugin is pretty much in opposition to Webpack's main goal and I imagine that many have used it as an anti-pattern in their builds. In my case, the real issue might be choice of tools (Astrum). However, the work to create a styleguide app from scratch in the time I have to do it is too much. For now I need to stick with a pre-made solution for the styleguide application, I might be able to reevaluate this decision after I reach 1.0.

**Comment by Franky47** [comment]
I have a use case, but I'm not sure yet if there's a better / more elegant solution.

I'm deploying my build folder to both Firebase Hosting and Surge.sh (for redundancy in case either service goes down). Firebase uses `index.html` as the entry point, and handles routing (the app is a SPA with router) by defining redirects. Surge uses a single `200.html` entry point to handle routing.

So I want the `index.html` (generated by webpack) to be copied as-is to `200.html`, then deploy each to their associated service.

However, at the moment I get an empty `200.html` file, but that is another issue.

**Comment by duivvv** [comment]
3 use cases I use this plugin for

- json files that get loaded with fetch
- responsive image assets (srcset)
- fonts that get loaded by WebFontLoader

Is there a way to avoid using copy-webpack-plugin for those @TheLarkInn ?

**Comment by kevlened** [comment]
@TheLarkInn I originally wrote the plugin to make it easier to build a Chrome extension with webpack.

Chrome extensions have several additional files (images, a manifest file, etc), that required the [file-loader](https://github.com/webpack/file-loader). I found the file-loader syntax cumbersome, so I wrote a cleaner interface (inspired by [transfer-webpack-plugin](https://github.com/molforp/transfer-webpack-plugin) which had missing features/no tests/too many issues to contribute). Ultimately, globs and ignores were added, exceeding the capabilities of file-loader.

I think the best use case for copy-webpack-plugin is when you're trying to copy a lot of files or you have complex requirements for the files you want to copy. In these cases, file-loader can fall short.

There are also existing projects that are being migrated to webpack from ant, grunt, or gulp. In these scenarios, this plugin makes it easier to transition from the task runner copy flows to full-blown webpack bundling.

Thanks for supporting webpack! It's truly changed my development productivity at work and home.

**Comment by valscion** [comment]
I'm trying to use this to output my sourcemap files to different folder than the rest of my assets, as I don't want my sourcemaps to be accidentally publicly accessible. I haven't figured out how to do that via normal webpack means, and I'd rather not just append another command after webpack builds as if that would fail, the sourcemap files might not be moved away from the bundle directory when they shouldn't have been there at all in the first place.

**Comment by Alex-Krautmann** [comment]
@valscion 

Off the top of my head a couple things to try

1) Filter out .map files at the server level
2) In the webpack config, do something different for dev vs. production and have npm scripts run one configuration or the other
    a) do something conditional based on NODE_ENV in webpack config `devtool: (NODE_ENV === 'dev) ? 'source-map' : '' `
    b) Preferred method is to have 3 webpack configs. webpack.base.config defines the base loaders, plugins and whatever. webpack.dev.config sets up dev onnly things like source maps. webpack.prod.config sets up things for production. Have your NPM scripts run command line webpack with whichever config is wanted. You could have a script for `npm run build:dev` and `npm run build:prod` 

```javascript
// webpack config
const isDevEnv = NODE_ENV === 'dev';
export default {
    devtool: (isDevEnv)
}
```

**Comment by valscion** [comment]
Thanks! I indeed wanted my sourcemaps to be available in _production_, so I need to come up with an option that:

a. never puts the sourcemaps in a directory that might be accessible without authentication
b. allows me to put the sourcemaps in the directory of my choosing

I eventually figured out that this plugin isn't what I should use, so I have one solution in mind that is more like the "filter on server level" thing. I don't want to add too complex post-build processing solutions — I'd rather leverage the core webpack tools so I won't have to do some unorthodox solutions.

But anyway, I don't think this issue is the place to debug my issues further, unless you want to ask some clarifying questions about the use case itself :smile:. I don't want to crowd this issue with unrelated messages ☺️

**Comment by ilyazub** [comment]
I have several files that should be required for specific domains. Configuration file looks like this:
```json
{
  "site1.com": "subfolder/file1.js",
  "site1.co.uk": "subfolder/file1.js",
  "site1.se": "subfolder/file1.js",
  "site4.com": "subfolder/file3.js",
  "site5.com": "subfolder/file2.js"
}
```
This configuration and webpack-generated mapping **shouldn't be added** to the bundle. That's why I'm **not using** `require.context`.
```javascript
var domain = parseDomainSomehow(window.location.hostname);
require('subfolder/' + domain + '.js');
```

Such requirement contradicts with webpack purpose. That's why I'm trying to use that plugin.
Yes, I know, this can be done with fairly simple Node.js script.
