### ISSUE TITLE
Сopy the directory itself

### ISSUE THREAD

**Issue by monolithed** [webpack-contrib/copy-webpack-plugin#89]
### Actual

```js
new CopyWebpackPlugin([
	{
		from: 'folder',
		to: 'folder'
	}
])
```

### Expected

```js
new CopyWebpackPlugin([
	{
		from: 'folder/'
	}
])
```

Output: `folder/files`

**Comment by kevlened** [comment]
We also have to support the use-case of copying the folder contents to the build directory. That's what currently happens when you omit `to`. In your suggestion, the only way to achieve copying folder contents to the build directory is with a blob.

```
new CopyWebpackPlugin([
	{
		from: 'folder/**/*'
	}
])
```

This may be more reasonable, but would be a pretty big breaking change.
