### ISSUE TITLE
[Feature] Passing throw loaders

### ISSUE THREAD

**Issue by andreicek** [webpack-contrib/copy-webpack-plugin#98]
Hi,

is it possible for the files to go thru the loaders? This way we can get fingerprinting of files, and etc.

Thanks

**Comment by jschroed91** [comment]
+1 on this - I have the same question. I'll post if I find a solution

**Comment by kevlened** [comment]
Maybe? This needs some investigation, but for now, you can perform file content modifications using the `transform` option.

**Comment by zonika** [comment]
@kevlened how would that work? 
For example, i want to compile a less file and then copy it into the build directory. (not using ExtractTextPlugin as I need to keep the files separate from one another and will link them in the html header using react-helmet only after a response from the server)

**Comment by sag1v** [comment]
@zonika i'm searching for the same thing (i think). copy `less` files but transform them to css while keeping the same structure. have you found a solution?

**Comment by DanielRuf** [comment]
Still relevant.

**Comment by DanielRuf** [comment]
See https://github.com/Klathmon/imagemin-webpack-plugin#example-usage

**Comment by IAMtheIAM** [comment]
This is still needed. Because using a loader doesnt work if you don't `require()` or `import` the file anywhere into the app.

**Comment by yuhr** [comment]
Any update on this?

**Comment by evilebottnawi** [comment]
@yuhr can you describe use case for this?

**Comment by yuhr** [comment]
@evilebottnawi [`html-webpack-plugin` does some kind of this](https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md#3-setting-a-loader-using-the-moduleloaders-syntax). I want to use the same loaders to perform transforming arbitrary files that are not `require`d by js as if they're `require`d. For example I have `src/*.md` and want them to be transformed into `dst/[name].html` applying PostHTML plugins, with `markdown-it-loader` and `posthtml-loader`, and at the same time I have to `require` some other `.md`s that are transformed in the same way. I think it's not simple that I need another system i.e. the `transform` option in order to achieve the same task as loaders.

**Comment by evilebottnawi** [comment]
Impossible due design reason, anyway we implement new hook in webpack for `copy` plugin before minimize step, it is allow to minimize/compress assets and change their in other hooks
